/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.WorkQueue.DoctorWorkRequest;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Doctor;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Shash
 */
public class RequestDoctorTestJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    
    /**
     * Creates new form RequestTransporTestJPanel
     */
    public RequestDoctorTestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        specialtext = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bandagetext = new javax.swing.JTextField();
        capsuletext = new javax.swing.JTextField();
        daystext = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        injectiontext = new javax.swing.JTextField();
        syruptext = new javax.swing.JTextField();
        submitAppJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        doctortext1 = new javax.swing.JTextField();

        valueLabel.setText("<value>");

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        jLabel6.setText("Specialization");

        specialtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialtextActionPerformed(evt);
            }
        });

        jLabel8.setText("Bandage");

        jLabel2.setText("Doctor");

        bandagetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandagetextActionPerformed(evt);
            }
        });

        capsuletext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capsuletextActionPerformed(evt);
            }
        });

        daystext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daystextActionPerformed(evt);
            }
        });

        jLabel9.setText("Injection");

        jLabel4.setText("Syrup");

        jLabel3.setText("Capsule");

        injectiontext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                injectiontextActionPerformed(evt);
            }
        });

        syruptext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syruptextActionPerformed(evt);
            }
        });

        submitAppJButton.setText("Submit Application");
        submitAppJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAppJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Available Doctor Information:");

        jLabel5.setText("Drug Distribution:");

        jLabel7.setText("Available Days");

        doctortext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctortext1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(53, 53, 53)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(specialtext, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(doctortext1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(42, 42, 42)))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(injectiontext, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bandagetext, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(74, 74, 74)
                                    .addComponent(daystext, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(capsuletext, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addGap(103, 103, 103)
                                .addComponent(submitAppJButton))
                            .addComponent(syruptext, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(valueLabel)))
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(doctortext1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(daystext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specialtext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(capsuletext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(syruptext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bandagetext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(injectiontext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton)
                    .addComponent(submitAppJButton))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void specialtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialtextActionPerformed

    private void bandagetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandagetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bandagetextActionPerformed

    private void capsuletextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capsuletextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capsuletextActionPerformed

    private void daystextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daystextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daystextActionPerformed

    private void injectiontextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_injectiontextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_injectiontextActionPerformed

    private void syruptextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syruptextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_syruptextActionPerformed

    private void submitAppJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAppJButtonActionPerformed
        DoctorWorkRequest request = new DoctorWorkRequest();

        if (daystext.getText().isEmpty() == true) {
            JOptionPane.showMessageDialog(null , " Doctor name cannot be empty");
            return;
        }
        if (specialtext.getText().isEmpty() == true) {
            JOptionPane.showMessageDialog(null , " specialization cannot Be Empty");
            return;
        }

              for (DoctorWorkRequest request1 : userAccount.getWorkQueue().getDoctorworkRequestList()){
//            if (specialtext.getText().equalsIgnoreCase(request1.getSpecialization())) {
//                JOptionPane.showMessageDialog(null , " You have already a specialization");
//                return;
//            }

        }

        if (capsuletext.getText().isEmpty() == true) {
            JOptionPane.showMessageDialog(null , "capsule name cannot be empty");
            return;
        }
        if (syruptext.getText().isEmpty() == true) {
            JOptionPane.showMessageDialog(null , " syrup name cannot Be empty");
            return;
        }
        if (bandagetext.getText().isEmpty() == true) {
            JOptionPane.showMessageDialog(null , " bandage name cannot Be empty");
            return;
        }
        if (injectiontext.getText().isEmpty() == true) {
            JOptionPane.showMessageDialog(null , " injection name cannot Be empty");
            return;
        }
        if (daystext.getText().isEmpty() == true) {
            JOptionPane.showMessageDialog(null , " Available days cannot Be empty");
            return;
        }
        
        

        String doctor = daystext.getText();
        String specialization = specialtext.getText();
        String capsule = capsuletext.getText();
        String syrup = syruptext.getText();
        String bandage = bandagetext.getText();
        String injection=injectiontext.getText();
        String days= daystext.getText();



        request.setDoctor(doctor);
        request.setSender(userAccount);
        request.setStatus("Sent");
        request.setSpecialization(specialization);
        //request.setReceiver(enterprise.);
        request.setCapsule(capsule);
        request.setSyrup(syrup);
        request.setBandage(bandage);
        request.setInjections(injection);
        request.setDays(days);
        //        Organization org = null;
        //        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            //            System.out.println(organization);
            //
            //            if (organization instanceof TeacherOrganization){
                //                org = organization;
                //                            System.out.println("yahan org aa gya");
                //
                //                break;
                //            }
            //        }
        //        if (org!=null){
            //            System.out.println("yahan aa gya");
            //            org.getWorkQueue().geteducationWorkLists().add(request);
            userAccount.getWorkQueue().getDoctorworkRequestList().add(request);
            System.out.println(enterprise.getWorkQueue().geteducationWorkLists());
            enterprise.getWorkQueue().getDoctorworkRequestList().add(request);
            JOptionPane.showMessageDialog(null, " Application Submission Successfull");
            // }

    }//GEN-LAST:event_submitAppJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        //        Component[] componentArray = userProcessContainer.getComponents();
        //        Component component = componentArray[componentArray.length - 1];
        //        VolunteerWorkAreaJPanel dwjp = (VolunteerWorkAreaJPanel) component;
        //        dwjp.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void doctortext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctortext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctortext1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField bandagetext;
    private javax.swing.JTextField capsuletext;
    private javax.swing.JTextField daystext;
    private javax.swing.JTextField doctortext1;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JTextField injectiontext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField specialtext;
    private javax.swing.JButton submitAppJButton;
    private javax.swing.JTextField syruptext;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
