/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerTeacherRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.TeacherOrganization;
import Business.Organization.Organization;
import Business.Organization.VolunteerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationWorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.VolunteerWorkRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.TeacherRole.RequestJobJPanel;

/**
 *
 * @author raunak
 */
public class VolunteerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization labOrganization;
    private WorkQueue workqueue;
    EcoSystem system;
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public VolunteerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.labOrganization = organization;
        this.system=system ;
        System.out.println(userAccount);
//        System.out.println(enterprise);
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)tblWork.getModel();
        
        model.setRowCount(0);
        for (VolunteerWorkRequest request : system.getWorkQueue().getVolWorkRequests()){
            Object[] row = new Object[8];
            row[0] = request;
            row[1] = request.getLocation();
            row[2] = request.getDate();
            row[3] = request.getDesc();
            row[4] = request.getInterested();
            row[5] = request.getSender();
            row[6] = request.getStatus();
//            String result = request.getTestResult();
//            row[7] = result == null ? "Waiting" : result;
            
            model.addRow(row);
        }
    }

    /**,0d is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblWork = new javax.swing.JTable();
        applyJobbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        tblWork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Event Name", "Location", "Date", "Work Description", "Interested"
            }
        ));
        jScrollPane2.setViewportView(tblWork);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 950, 210));

        applyJobbtn.setText("Volunteer For Work");
        applyJobbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyJobbtnActionPerformed(evt);
            }
        });
        add(applyJobbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("APPLY FOR VOLUNTEERING");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void applyJobbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyJobbtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblWork.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please Select One");
            return;
        }
        VolunteerWorkRequest request = (VolunteerWorkRequest)tblWork.getValueAt(selectedRow, 0);
        //request.setReceiver(userAccount);
        
        request.setInterested(userAccount);
        request.getApplicants().add(userAccount.getUsername());
        request.getInterested();
        populateTable();
    }//GEN-LAST:event_applyJobbtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyJobbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblWork;
    // End of variables declaration//GEN-END:variables
}
